### ISSUE TITLE
Get ready for demo

### ISSUE THREAD

**Issue by AbeJellinek** [Aiybe/xmptest#10]
- Documentation
- Support all formats
- Better design
- Attachment location (nameddest?)

**Comment by masinter** [comment]
Stuff to do today:

prepare for demo for JAR
 to  show new features
  clean up repo to make github project self-explanaaatory

fix up README.md
      pointer to server
       add demo script to project

Make sure service is deployed
   Amazon server
   set up deployment scripts and instructions
   Fix up HTML to make it using it self-explanatory

work on demo
    example PDFs without data
                     data files

find more examples

let example take a URL as well as file upload (?)

prepare demo script, e.g.

```
 * show github project
* show PDF Files & data files
* invoke write to create PDF with data
* show read
```
