### ISSUE TITLE
Error using PDFData to view data embedded in a PDF produced by PDFData tool

### ISSUE THREAD

**Issue by hjellinek** [Aiybe/xmptest#12]
I'm using https://pdf.abe.im.

I downloaded [a section of the Statistical Abstract of the US (2012)](http://www.census.gov/library/publications/2011/compendia/statab/131ed/health-nutrition.html) and used the PDFData tool to embed [one of its source tables](http://www2.census.gov/library/publications/2011/compendia/statab/131ed/tables/12s0214.xls) in it, then took the output of that and added [a second CSV](http://www2.census.gov/library/publications/2011/compendia/statab/131ed/tables/12s0215.xls) to it.  I did not add fragment identifiers to either one.
[health_data_data.pdf.zip](https://github.com/Aiybe/PDFData/files/453045/health_data_data.pdf.zip)

When I uploaded the resulting file (attached to this issue) to https://pdf.abe.im/read/upload to view it, I received this error:

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Fri Sep 02 22:58:37 UTC 2016
There was an unexpected error (type=Internal Server Error, status=500).
Error: Expected a long type at offset 4390893, instead got 'olumn_right'
```

**Comment by AbeJellinek** [comment]
Will look into this. Likely(?) an issue with the PDF library, but I might be able to come up with a fix.

**Comment by AbeJellinek** [comment]
I tried this using the steps that you listed and couldn't reproduce on my end. Here's [my resulting PDF file](https://github.com/Aiybe/PDFData/files/458066/health_data_data.pdf) -- does it work for you?

**Comment by hjellinek** [comment]
Yes, it works now.  You updated PDFBox in the meantime, so I assume it was a PDFBox problem.

**Comment by hjellinek** [comment]
I should have said that that file you linked to was correct, but as of 9/7 the Web service still does not create well-formed PDFs for the case I described.

Can you push the latest code to the server?

**Comment by hjellinek** [comment]
OK, the server is now running the right code, and it no longer crashes on my test case above.

However, the embedded CSV information is garbled!  I will submit a new bug report for that.
