### ISSUE TITLE
Regression: PDFData produces or extracts gibberish

### ISSUE THREAD

**Issue by hjellinek** [Aiybe/xmptest#14]
I had previously encountered a crash bug when embedding a CSV in a file that already had one embedded in it.  The fix for that was to update PDFData to use the latest PDFBox.

The good news is that the server no longer crashes.  The bad news is that the server is now producing bad output.

Test case:
- I used the PDFData server to embed the attached CSV in the attached PDF.
- I used the PDFData server to upload the PDF and view the CSV.
- I used the PDFData server to upload the PDF and download the CSV.

Alas, the CSV output is gibberish in both the view and download cases.

Input PDF: [health.pdf](https://github.com/Aiybe/PDFData/files/470747/health.pdf)
The input CSV (GitHub forced me to compress it in order to attach it to this report):
[12s0214.xls](https://github.com/Aiybe/PDFData/files/470751/12s0214.xls.zip)

Here's the resulting PDF with bad embedded data:
[health_data1-bad.pdf](https://github.com/Aiybe/PDFData/files/470768/health_data1-bad.pdf)

**Comment by AbeJellinek** [comment]
Make sure to convert Excel files to CSV before uploading! Excel format isn't currently supported.

**Comment by hjellinek** [comment]
Ah, good point.   :-)  Yet I think it worked (for some value of "worked") with a single file.  I will convert the files to CSV from XLS and try again.
