### ISSUE TITLE
PDFData Read produces a ZIP file named "upload" with no extension

### ISSUE THREAD

**Issue by hjellinek** [Aiybe/xmptest#15]
It would be convenient if the download file had the ".zip" extension.

It would be icing on the cake if the main part of the file name bore some relationship to the original name of the embedded CSV, CSV fragment name, or even the PDF file's name.  In that last case, if the input PDF were `health.pdf`, the extracted CSV could be named `health.csv.zip`, for instance.

**Comment by AbeJellinek** [comment]
Mostly fixed in b776dd4d3fe9599f8f00be194e8b34039849db82.
