### ISSUE TITLE
Server error on embedding 5th CSV in PDF

### ISSUE THREAD

**Issue by hjellinek** [Aiybe/xmptest#19]
My Statistical Abstract example uses one chapter of the Statistical Abstract of the US (2012) and 5 of the chapter's tables, converted from XLS to CSV.

As luck would have it, I get an error when embedding file number 5.

![screenshot_584](https://cloud.githubusercontent.com/assets/4968570/18522493/26eac7e6-7a65-11e6-9a06-54dff2cfcb16.png)

[PDF with first 4 files embedded](https://github.com/Aiybe/PDFData/files/472874/health_data_4.pdf)

[The fatal CSV, compressed](https://github.com/Aiybe/PDFData/files/472876/12s0218.csv.zip)

**Comment by AbeJellinek** [comment]
Issue seems to be fixed if you start from scratch with current version.
