### ISSUE TITLE
output should default to returning triples

### ISSUE THREAD

**Issue by masinter** [Aiybe/xmptest#3]
Similar to what the HTML/RDFa renderer does, the output should preferably in terms of triples, in Turtle or OWL or JSON-LD. Perhaps the library has a call-back to generate triples.

**Comment by AbeJellinek** [comment]
I worked a little on this in 7cb94c1db44f48e98d4cbcf60b0856ff0fda1a34, but the output is still pretty ugly. It is triples, though, so that's a start.
