### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by masinter** [Aiybe/xmptest#9]
Maybe make a separate BUILD.md to isolate build instructions from README.md?

Currently, getting errors

Error:(3, 34) java: package com.fasterxml.jackson.core does not exist
Error:(4, 38) java: package com.fasterxml.jackson.databind does not exist
Error:(85, 54) java: cannot find symbol
  symbol:   class JsonProcessingException
  location: class me.abje.xmptest.Table
Error:(97, 24) java: cannot find symbol
  symbol:   class ObjectMapper
  location: class me.abje.xmptest.Table
Error:(99, 24) java: cannot find symbol
  symbol:   class ObjectMapper
  location: class me.abje.xmptest.Table

**Comment by AbeJellinek** [comment]
Whenever you have an issue like this, the most likely fix is just to refresh the Gradle project in IntelliJ. It's usually just a case of IntelliJ's project model being out of sync with Gradle's.

You can refresh the project by opening the Gradle panel in IntelliJ and clicking the blue Refresh button. Let me know if that fixes the issue!
